apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
      - name: comments
        image: codenameninja/comments

---

apiVersion: v1
kind: Service
metadata:
  name: comments-srv
  labels:
    app: comments-srv
spec:
  type: ClusterIP #Optional
  selector:
    app: comments
  ports:  # List of ports to be exposed
    - name: comments 
      protocol: TCP
      port: 4001
      targetPort: 4001