apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - name: event-bus
        image: codenameninja/event-bus

---

apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
  labels:
    app: event-bus-srv
spec:
  type: ClusterIP #Optional
  selector:
    app: event-bus
  ports:  # List of ports to be exposed
    - name: event-bus 
      protocol: TCP
      port: 4005
      targetPort: 4005