apiVersion: v1
kind: Service
metadata:
  name: posts-srv
  labels:
    app: posts-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:  # List of ports to be exposed
    - name: posts 
      protocol: TCP
      port: 4000
      targetPort: 4000