apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: codenameninja/posts
---

apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
  labels:
    app: posts-clusterip-srv
spec:
  type: ClusterIP #Optional
  selector:
    app: posts
  ports:  # List of ports to be exposed
    - name: posts 
      protocol: TCP
      port: 4000
      targetPort: 4000