apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
      - name: query
        image: codenameninja/query

---

apiVersion: v1
kind: Service
metadata:
  name: query-srv
  labels:
    app: query-srv
spec:
  type: ClusterIP #Optional
  selector:
    app: query
  ports:  # List of ports to be exposed
    - name: query 
      protocol: TCP
      port: 4002
      targetPort: 4002